import Container from "@/app/ui/team/contFile";
import ContainerRev from "@/app/ui/team/contRfile";

export default function Page() {
    return(<div>
        <Container source="/Images/Sahib_img.jpg" desig="Founder & CEO" name="Mr. Sahibpreet Singh"  desp="Mr. Singh is an Experienced Data Scientist with a focus on NLP, Conversational AI, and Generative AI. He has been Recognized as a top mentor on Kaggle, positioned in the uppermost 0.01% percentile. Adept at both collaborative teamwork and leadership, possessing outstanding communication proficiency. Mr. Singh is Devoted to providing advanced solutions that unveil concealed value within textual data and has been Demonstrating robust analytical skills and an enthusiastic drive for producing meaningful outcomes."/>
        <ContainerRev source="/Images/Simran_img.jpeg" desig="COO" name="Mr. Simrandeep Singh"  desp=" Mr. Singh is a Devoted Professional Who has proven analytical excellence in Data Analytics.Mr. Singh has been a critical Content writer on LinkedIn focussing on youth employment and education at the platform.With Major focus on youth employability. Along With that he possesses advanced skills in Data analytic in Excel,SQl,Power BI and Tableau he has Contributed in some crucial data visualization projects."/>
        <Container source="/Images/Pranav_img.jpg" desig=" Mentor, Back-End Development " name="Mr. Pranav Gupta"  desp="Mr. Kumar is an Innovative IT professional with a proven track record of over 6 years in the industry, fueling business success through cutting-edge solutions. His expertise lies in Microsoft technologies, including MVC, .NET Core, and Azure, coupled with a solid grasp of frontend technologies like Angular and React. He is keen to explore new opportunities in the ever-evolving IT field, where I can contribute my skills and expertise to drive impactful change."/>
        <ContainerRev source="/Images/Navjot_img.jpeg" desig="Front-End Developer" name="Mr. Navjot Singh"  desp="An ambitious and dedicated Computer Science Engineering student at Chitkara University specializing in Front-End Development. With a profound expertise in technologies such as React, Next.js, Bootstrap, and Tailwind CSS, I have honed my craft in creating captivating and user-centric web experiences. My journey as a front-end developer is fueled by a passion for innovation and a relentless pursuit of mastering emerging technologies."/>
    </div>);
}